name: "Hello world workflow"

# Controls when the actions will run.
# Triggers the workflow on push events to main or production branch
on:
  push:
    branches:
      - main
      - production

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "hello world"
        

      - name: "print current date"
        run: date

      - name: "print who are u"
        run: whoami
