name: "Multi event pipeline / workflow" # Name of the pipline

on:
  push: # Event: Whenever a push is made to the repository on the master branch
    branches:
      - master
      - test
  pull_request: # Event: Whenever a pull request is made to the repository
    branches:
        -master       

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps: # steps to exectied in the jon
      - name: "Running on master/test push"
        run: echo "running on master push"

  on-pull-request:
    if: github.event_name == 'pull'
    runs-on: ubuntu-latest
    steps: # steps to exectied in the jon
      - name: "Running on pull request"
        run: echo "running on pull requestS"

